<a href="https://colab.research.google.com/github/jayalakshmikonduboyena/python-lab/blob/main/Copy_of_Konduboyena_Jaya_lakshmi_19A21A0591i.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NAME: konduboyena jaya lakshmi
 
Regno:19A21A0591
 
Sec:CSE-B

  EXCERSICE-1 A.WRITE PROGRAM IN INTERACTIVE,INTERPRETER,PYHON SCRIPT MODE.
 
 
 B.Write a program to purposefully raise Indentation Error and Correct it

AIM :Running instructions in Interactive interpreter and a Python Script 

DESCRIPTION:


   Python is a high-level, interpreted, interactive and object-oriented scripting language. Python is 
designed to be highly readable. It uses English keywords frequently where as other languages 
use punctuation, and it has fewer syntactical constructions than other languages. 


.Python is Interpreted 

.Python is Interactive

.Python is Object-Oriented 

.Python is a Beginner's Language 

Python Programming Running Python Scripts

Running Python in THREE ways:

a) Running Python Interpreter

b) Running Python Scripts in IDLE

c) Running python scripts in Command Prompt

a)  Running Python Interpreter: Python comes with an interactive interpreter. 
When you type python in your shell or command prompt, the python interpreter becomes active with a >>> prompt and waits for your commands 

b)  Running Python Scripts in IDLE: . Go to File menu click on New File (CTRL+N) and write the code and save first.py 

c)  Running python scripts in Command Prompt: ** **bold text · Before going to run we have to check the PATH in environment variables. 

In [ ]:
 a=78
b=89
a,b=b,a
print(a,b)

89 78


 AIM:
Write a program to purposefully raise Indentation Error and Correct it

 DESCRIPTION: 

 Intentation :

.Python does not support braces to indicate blocks of code for class and function definitions or flow control. 

.Blocks of code are denoted by line indentation. 

.All the continuous lines indented with same number of spaces would form a block

. Python strictly follow indentation rules to indicate the blocks

In [ ]:
 a=input("enter a vlaue:")
b=input("enter b value:")
c=a+b;
print("sum is ",c,sep="\t")
c=int(a)+int(b)
print("sum of {} and {} is : {}".format(a,b,c))
print("sum of %s and %s is:%d"%(a,b,c))
x=10
y=123
z=x+y;
print("sum is",z,sep='\t' )

enter a vlaue:2
enter b value:3
sum is 	23
sum of 2 and 3 is : 5
sum of 2 and 3 is:5
sum is	133


In [ ]:
 print("welcome to python")
a=20
b=30
print("the value of a:",a)
print("the value of b :",b)
if(a>b):
       print("a is big");
       print("ifbblock ends")
else:
            print("b is big")
            print("elseblock ends")

welcome to python
the value of a: 20
the value of b : 30
b is big
elseblock ends


 EXERCISE-2
A.COMPUTE DISTANCE BETWEEN TWO POINTS
 
 
B.TAKE TWO NUMBERS ON COMMAND LINE ARGUMENTS AND PRINT THE SUM

 AIM: 
TO Write a program to compute distance between two points taking input from the user(PythagoreanTheorem)

 DESCRIPTION:


Taking Input From the User: A function is defined as a block of organized, reusable code used to perform a single, related action. Python has many built-in functions; you can also create your own. Python has an input function which lets you ask a user for some text input. You call this function to tell the program to stop and wait for the user to key in the data. In Python 2, you have a built-in function raw_input(), whereas in Python 3, you have input(). The program will resume once the user presses the ENTER or RETURN key. 
Input Function input(prompt=None,/). Read a string from standard input. The trailing newline is stripped. The prompt string, if given, is printed to standard output without a trailing newline before reading input. If the user hits EOF (*nix: Ctrl-D, Windows: Ctrl Z+Return), raise EOFError.

In [ ]:
 x1=10
x2=80
y1=12
y2=20
z=(pow((x2-x1),2)+pow((y2-y1),2))**0.5
print(z)

70.45565981523414


In [ ]:
 import math
x1=int(input("enter  x1 value:"))
x2=int(input("enter  x2 value:"))
y1=int(input("enter  y1 value:"))
y2=int(input("enter  y2 value:"))
z=math.sqrt((x2-x1)**2+(y2-y1)**2)
print("the distance between two points is :",z)
print("the distance between two points is :",z,sep='\t')
print("the distance between ({}, {})and ({},{}) is  :{}".format(x1,y1,x2,y2,z))
 
print("the distance between (%d, %d)and (%d,%d) is  :%f"%(x1,y1,x2,y2,z))

enter  x1 value:2
enter  x2 value:3
enter  y1 value:4
enter  y2 value:5
the distance between two points is : 1.4142135623730951
the distance between two points is :	1.4142135623730951
the distance between (2, 4)and (3,5) is  :1.4142135623730951
the distance between (2, 4)and (3,5) is  :1.414214


AIM:
To Write a program add.py that takes 2 numbers as command line arguments and prints its sum

DESCRIPTION:

The arguments that are given after the name of the program in the command line shell of the operating system are known as Command Line Arguments. Python provides various ways of dealing with these types of arguments. The three most common are: Using  sys.argv Using getopt module Using argparse module Using sys.argv The sys module provides functions and variables used to manipulate different parts of the Python runtime environment. This module provides access to some variables used or maintained by the interpreter and to functions that interact strongly with the interpreter. One such variable is sys.argv which is a simple list structure. It’s main purpose are: It is a list of command line arguments. len(sys.argv) provides the number of command line arguments.   import sys

In [ ]:
 import sys
a=sys.argv[1]
b=sys.argv[2]
sum=int(a)+int(b)
print("summ of two number is:",sum)

 EXCERSCISE-3 A) Write a Program for checking whether the given number is an even number or not.
 
 
b) Using a for loop, write a program that prints out the decimal equivalents of 1/2, 1/3, 1/4, . . .1/10
 
 
c) Write a program using a for loop that loops over a sequence. What is sequence?
 
d) Write a program using a while loop that asks the user for a number, and prints a countdownfrom that number to zero

  AIM: 
 
a) Write a Program for checking whether the given number is an even number or not.

 DESCRIPTION: 
 
 if..else Statement When there is an alternate operation in control flow, use an else statement alongside with if statement. The general format is if condition:

In [ ]:
 n=int(input("enter a number:"))
if (n%2)==0:
        print("given number is even")
else:
      print("given number is odd")

enter a number:2
given number is even


AIM:
 
Using a for loop, write a program that prints out the decimal equivalents of 1/2, 1/3, 1/4, . . 10

 DESCRIPTION 
   For Loop: For loops can iterate over a sequence of numbers using the "range" and "xrange" functions. The difference between range and xrange is that the range function returns a new list with numbers of that specified range, whereas xrange returns an iterator, which is more eficient. The general format is for x in range(start,stop,step): statements

In [ ]:
 n=int(input("enter a number:"))
for i in range(2,n):
    de=1/i;
    print("1/",i,"=",de)

enter a number:3
1/ 2 = 0.5


 AIM:
 
 
 Write a program using a for loop that loops over a sequence. What is sequence?

 DESCRIPTION:
 For Loop: For loops can iterate over a sequence of numbers using the "range" and "xrange" functions. The difference between range and xrange is that the range function returns a new list with numbers of that specified range, whereas xrange returns an iterator, which is more eficient. The general format is for x in range(start,stop,step): statements

In [ ]:
 #program using a for a loop that loops over a sequence
print("loop sequence")
num=[45,25,2,28,3,25]
for i in num:
    print(i)
 
#string sequence
print("string sequence")
days=["sun","mon","tue","wed","thur","fri","st"]
for d in days:
    print(d)
    
#bothh sequence
print("sequence")
arr=[123,"abc",5.6,'h',-33,"xy",True]
for x in arr:
      print(x)

loop sequence
45
25
2
28
3
25
string sequence
sun
mon
tue
wed
thur
fri
st
sequence
123
abc
5.6
h
-33
xy
True


AIM: 


 TO Write a program using a while loop that asks the user for a number, and prints a 
countdownfrom that number to zero.

DESCRIPTION: 



While Loop is used to execute a block of statements repeatedly until a given condition is 
satisfied. And when the condition becomes false, the line immediately after the loop in the 
program is executed. While loop falls under the category of indefinite iteration 
The syntax for a while loop is: 
while [ condition] 

In [ ]:
 #countdown seq
n=int(input("enter the numbr:"))
while n>0:
      print(n)
      n=n-1

enter the numbr:3
3
2
1


 EXCERCISE-4 a) Find the sum of all the primes below two million. Each new term in the Fibonacci sequence is generated by adding the previous two terms. Bystarting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 
b) By considering the terms in the Fibonacci sequence whose values do not exceed four million,find the sum of the even-valued terms.

AIM: 


 a)  Find the sum of all the primes below two million. Each new term in the Fibonacci sequence is 
generated by adding the previous two terms. Bystarting with 1 and 2, the first 10 terms will be: 1, 
2, 3, 5, 8, 13, 21, 34, 55, 89, ...

DESCRIPTION: 



A Fibonacci sequence is the integer sequence of 0, 1, 1, 2, 3, 5, 8.... 

The first two terms are 0 and 1. All other terms are obtained by adding the preceding two terms. 
This means to say the nth term is the sum of (n-1)th and (n-2)th term 
Here, we store the number of terms in nterms. We initialize the first term to 0 and the second 
term to 1. 


If the number of terms is more than 2, we use a while loop to find the next term in the sequence 
by adding the preceding two terms. We then interchange the variables (update it) and continue 
on with the process. 

In [ ]:
 n=int(input("enter   a anum:"))
a=0
b=1
c=a+b
st=""
sum=0
con=0
while con<=n:
    st+=""+str(c)
    sum+=c        
    a=b
    b=c 
    c=a+b
    con+=1
print(st)
print("sum of fibonacii series:",sum)

enter   a anum:3
1235
sum of fibonacii series: 11


AIM: 



 b)  By considering the terms in the Fibonacci sequence whose values do not exceed four 
million,find the sum of the even-valued terms. 

DESCRIPTION:


A Fibonacci sequence is the integer sequence of 0, 1, 1, 2, 3, 5, 8.... 
The first two terms are 0 and 1. All other terms are obtained by adding the preceding two terms. 
This means to say the nth term is the sum of (n-1)th and (n-2)th term 
Here, we store the number of terms in nterms. We initialize the first term to 0 and the second 
term to 1. 


If the number of terms is more than 2, we use a while loop to find the next term in the sequence 
by adding the preceding two terms. We then interchange the variables (update it) and continue 
on with the process. 

In [ ]:
 n=int(input("enter a number:"))
c=0
 
 
st=""
sum=0
 
for i in range(2,n):
 state=True
for j in range(2,i):
 if(i%j==0):
        state=False
        break;
if state==True:
            st+=""+str(i)
            c+=1
            sum+=i
 
print("prime numbers")
print(st)
 
print("total count of the prime numbers:",c)
print("sum of all prime nums:",sum)

IndentationError: ignored

 EXCERCISE-5DS
a) Write a program to count the numbers of characters in the string and store them in adictionary data structure
 
b) Write a program to use split and join methods in the string and trace a birthday with adictionary data structure.

AIM: 



 a) Write a program to count the numbers of characters in the string and store them in 
adictionary data structure 

DESCRIPTION: 



Given a string, the task is to find the frequencies of all the characters in that string and return a 
dictionary with key as the character and its value as its frequency in the given string.


Method #1 :
     Naive method 
Simply iterate through the string and form a key in dictionary of newly occurred element or if 
element is already occurred, increase its value by 1. 


Method #2 :
     Using collections.Counter() 
The most suggested method that could be used to find all occurrences is this method, this 
actually gets all element frequency and could also be used to print single element frequency if 
required. 

In [ ]:
 name=input("enter anmae:")
dic={}
for ch in name:
    keys=dic.keys()
 
    if(ch in keys):
        dic[ch]=dic[ch]+1
    else:
        dic[ch]=1
 
print("dictinarry is:",dic)

enter anmae:3
dictinarry is: {'3': 1}


AIM: 



 b) Write a program to use split and join methods in the string and trace a birthday with 
adictionary data structure 

DESCRIPTION: 



Python program to Split a string based on a delimiter and join the string using another delimiter. 


Split a string can be quite useful sometimes, especially when you need only certain parts of 
strings. A simple yet effective example is splitting the First-name and Last-name of a person.


Another application is CSV(Comma Separated Files). We use split to get data from CSV and join 
to write data to CSV. 
In Python, we can use the function split() to split a string and 
join() to join a string. 

In [ ]:
 dob={"jaya":"09-01-2002","slsd":"14-04-2002"}
name=input("enter which person dob u want:")
l=name.split()
birth=""
for i in l:
    if i in dob.keys():
        pers=i
 
print("".join([pers,"birthdayis:",dob[pers]]))

enter which person dob u want:jaya
jayabirthdayis:09-01-2002


 EXERCISE-6 DS - Continued
 
a) Write a program combinelists that combines these lists into a dictionary.
 
b) Write a program to count frequency of characters in a given file. Can you use characterfrequency to
 
tell whether the given file is a Python program file, C program file or a text file?

AIM: 


a) Write a program combinelists that combines these lists into a dictionary.

DESCRIPTION:

   For this, simply declare a dictionary, and then run nested loop for both the lists and assign key 
and value pairs to from list values to dictionary. 
Most pythonic and generic method to perform this very task is by using zip(). 

This function pairs 
the list element with other list element at corresponding index in form of key-value pairs. 

In [ ]:
 sub=["daa","os","dbms","p&s","ppl","se"]
marks=[85,96,75,65,83,56]
print(sub)
print(marks)
dic=dict(zip(sub,marks))
print(dic)

['daa', 'os', 'dbms', 'p&s', 'ppl', 'se']
[85, 96, 75, 65, 83, 56]
{'daa': 85, 'os': 96, 'dbms': 75, 'p&s': 65, 'ppl': 83, 'se': 56}



AIM: 


 b) Write a program to count frequency of characters in a given file. Can you use 
characterfrequency to tell whether the given file is a Python program file, C program file or a text 
file? 

DESCRIPTION: 


approaches to count the number of times a letter appears in a text file in Python. 


Method 1: Using the in-built count() method. 
Approach: 

1. Read the file. 

2. Store the content of the file in a variable. 

3. Use the count() method with the argument as a letter whose frequency is required.
 
4. Display the count of the letter

In [ ]:
 filetypes=['.py','.c','.txt']
fn=input("enter a fikle name:")
f=open(fn,"r")
count=dict()
for  ft in filetypes:
     if(ft in  fn):
           if(ft==".py"):
             print("python file")
           elif(ft==".c"):
             print("cfile")
           elif(ft==".txt"):
             print("text file")
 
 
for line in f:
     for ch in line:
          if ch in count:
               count[ch]=count[ch]+1
 
          else:
              count[ch]=1
 
 
print(count)
f.close()

KeyboardInterrupt: ignored

 EXCERCISE-7
 
7 Files
 
a) Write a program to print each line of a file in reverse order.
 
b) Write a program to compute the number of characters, words and lines in a file.

AIM 


a)  Write a program to print each line of a file in reverse order. 

DESCRIPTION: 


The file handling plays an important role when the data needs to be stored permanently into the 
file. A file is a named location on disk to store related information. We can access the stored 
information (non-volatile) after the program termination. In Python, files are treated in two 
modes as text or binary. The file may be in the text or binary format, and each line of a file is 
ended with the special character. Hence, a file operation can be done in the following order.

□ Open a file 

□ Read or write - Performing operation 

□ Close the file 

In [ ]:
 obj=open("sam.txt","r")
if obj:
    st=obj.read()
    print("file content is:")
obj.close()
print()
lines=st.split('\n')
for ln in lines:
    i=len(ln)-1
    while(i>=0):
      print(ln[i],end='')
      i=i-1
    print()

AIM: 

 b)  Write a program to compute the number of characters, words and lines in a file 

DESCRIPTION: 

 Given a text file fname, the task is to count the total number of characters, words, spaces and 
lines in the file.

As we know, Python provides multiple in-built features and modules for handling files. Let’s 
discuss different ways to calculate total number of characters, words, spaces and lines in a file 
using Python. 

Method #1: Naive approach 

In this approach, the idea is to solve the task by developing our own logic. Without using any 
built-in function of Python, the total number of characters, words, spaces and lines of the file will 
be calculated. 

Method #2: 
Using some built-in functions and OS module functions 
In this approach, the idea is to use the os.linesep() method of OS module to separate the lines 
on the current platform. When the interpreter’s scanner encounter os.linesep it replaces it with 
\n character. After that strip() and split() functions will be used to carry out the task. 

In [ ]:
 obj=open("sam.txt","r")
if obj:
    st=obj.read()
    print("file content is:")
obj.close()
print()
nc=nw=nl=0
for ch in st:
    if(ch):
        nc=nc+1
    if(ch==''):
        nw=nw+1
    if(ch=='\n'):
        nl=nl+1
 
print("number of characters in a file:",nc)
print("number of words in file is:",nw)
print("number of lines ins file:",nl)

 EXCERCISE-8
 
 
   8 Functions'
 
a) Write a function ball collide that takes two balls as parameters and computes if they arecolliding. Your function should return a Boolean representing whether or not the balls arecolliding. Hint: Represent a ball on a plane as a tuple of (x, y, r), r being the radius If (distance between two balls centers) <= (sum of their radii) then (they are colliding)
 
b) Find mean, median, mode for the given set of numbers in a list.

AIM: 



a) Write a function ball collide that takes two balls as parameters and computes if they 
arecolliding. Your function should return a Boolean representing whether or not the balls 
arecolliding.


Hint: Represent a ball on a plane as a tuple of (x, y, r), r being the radius If (distance between two 
balls centers) <= (sum of their radii) then (they are colliding)

DESCRIPTION :


Functions A function in python is a block of code that is defined for doing frequent operations in 
a particular task. The general format is 
def Functionname(arguments): 
 Statements 


 
 
Calling a Function: 

A function can be called by its name followed by arguments within parenthesis. 
function() 

In [ ]:
 import math
def ballcollide(b1tup,b2tup):
    x1=b1tup[0]
    y1=b1tup[1]
    x2=b2tup[0]
    y2=b2tup[1]
    r1=b1tup[2]
    r2=b2tup[2]
 
 
    d=math.sqrt((x2-x1)**2+(y2-y1)**2)
    if(d<=r1+r2):
      return True
    else:
        return False
 
 
ball1=(1,2,3)
ball2=(3,2,1)
c=ballcollide(ball1,ball2)
if(c):
    print("balls are collided")
else:
    print("ball are not collided")

AIM:


 b) Find mean, median, mode for the given set of numbers in a list 

DESCRIPTION :

Mean :
   The mean is the average of all numbers and is sometimes called the arithmetic mean. 
This code calculates Mean or Average of a list containing numbers: 

Median : 
   The median is the middle number in a group of numbers. This code calculates Median 
of a list containing numbers: 

Mode : 
The mode is the number that occurs most often within a set of numbers. This code 
calculates Mode of a list containing numbers: 
We will import Counter from collections library which is a built-in module in Python 2 and 3.
 This 
module will help us count duplicate elements in a list. We define a list of numbers and calculate 
the length of the list. We then call Counter (a dict subclass) which helps to count hashable 
objects, and we then convert it to dict object. We then initialize a list with a For Loop to compare 
all the dict values (Number of elements) to the max of all dict values (count of most occurring 
element) and it returns all the elements equal to max count. If the elements returned are equal to 
the number of total elements in a list then we print out ‘No mode’, else we print out the modes 
returned.

In [ ]:
 def mean(numlist):
    return sum(numlist)/len(numlist)
def median(numlist):
    numlist.sort()
    print(numlist)
    n=len(numlist)
    print("total",n)
    mid=n//2
    print("mid:",mid)
    if(n%2==0):
        return numlist[mid]
    else:
        return (numlist[mid-1]+numlist[mid])/2
def mode(numlist):
    numlist.sort()
    temp=[]
    i=0
    while i<len(numlist):
        temp.append(numlist.count(numlist[i]))
        i+=1
    dic=dict(zip(numlist,temp))
    modes={k for k, v in dic.items() if(v==max(temp))}
    return modes
list=[1,1,2,2,3,4,5,3,3]
print("mean of guive list:",mean(list))
print("median of guive list:",median(list))
 
print("mode of guive list:",mode(list))

 Exercise - 9 
Functions - Continued
 
a) Write a function nearly equal to test whether two strings are nearly equal. Two strings a and bare nearly equal when a can be generated by a single mutation on b.
 
b) Write a function dup to find all duplicates in the list.
 
c) Write a function unique to find all the unique elements of a list.

AIM: 


a) Write a function nearly equal to test whether two strings are nearly 



DESCRIPTION: 



strlen() function is used to check wether the two string are nearly equal or not by basis of the 
Length of those Strings
 len() function is an inbuilt function in Python programming language that returns the length of 
the string.

len() is a built-in function in python.You can use the len() to get the length of the given string, 
array, list, tuple, dictionary, etc. 

Value: the given value you want the length of.
 
Return value a return an integer value i.e. the length of the given string, or array, or list, or 
collections. 
Syntax: 

In [ ]:
 def nearlyeq(str1,str2):
    count=0
    i=j=0
    ss=0
    while(i<len(str1)and j<len(str2)):
        if(str1[i]!=str2[j]):
            count+=1
        if(len(str1)>len(str2)):
            i+=1
 
        elif(len(str1)==len(str2)):
            pass
        else:
            i-=1     
        if(count>1):
             ss-=1
             
        i+=1
        j+=1
        if(count<2):
             ss+=1
 
    return ss
s1=input("enter a string 1:")
s2=input("enter the string2:")
t=nearlyeq(s1,s2)
if(t>1):
    print("neraly equal0")
else:
    print("not nearly equal")

AIM: 

 b) Write a function dup to find all duplicates in the list.

DESCRIPTION: 

To check if a list contains any duplicate element follow the following steps, 

1. Add the contents of list in a set.

As set contains only unique elements, so no duplicates will be added the the set.  
 
 
2. Compare the size of set and list. 
 
If size of list & set is equal then it means no duplicates in list.  
 
 
3. If size of list & set are different then it means yes, there are duplicates in list.

In [ ]:
 def dup(list):
  list1=[]
  for i in list:
    count=list.count(i)
    if(count>1 and (i not in list1)):
        list1.append(i)
        
  print("the dups int he list are:",list1)        
list2=[1,2,1,2]
 
dup(list2)

AIM: 

 c) Write a function unique to find all the unique elements of a list.

DESCRIPTION:


To find the unique in the list .There is a Specific Method i.e., 

Method : Traversal of list 

Using traversal, we can traverse for every element in the list and check if the element is in the 
unique_list already if it is not over there, then we can append it in the unique_list. 
This is done using one for loop and other if statement which check if the value is in the unique 
list or not which is equivalent to another for loop. 

In [ ]:
 def unique(list1):
  list2={}
 
  for i in list1:
    c=list1.count(i)
    if c==1:
      list2[i]=c
  print("the unique elements in the list are:",list2)
 
list=[1,2,3,45,45,6,88,88,9]
unique(list)

 Exercise - 10
 - Functions - Problem Solving
 
a) Write a function cumulative product to compute cumulative product of a list of numbers.
 
b) Write a function reverse to reverse a list. Without using the reverse function.
 
c) Write function to compute gcd, lcm of two numbers. Each function shouldn’t exceed one line

AIM: 


a) Write a function cumulative product to compute cumulative product of a list of numbers. 

DESCRIPTION: 


A cumulative product is a sequence of partial products of a given sequence. For example, the 
cumulative products of the sequence. , are , , .. Cumulative products can be implemented in the 
Wolfram Language as Rest[FoldList[Times, 1, list]] 

cumprod(A,1) works on successive elements in the columns of A and returns the 
cumulative  products  of  each  column.  cumprod(A,2)  works  on  successive  elements  in  the 
rows of A and returns the cumulative products of each row.
 
umprod() function is used when we want to compute the cumulative product of array elements 
over a given axis. Syntax : numpy.cumprod(arr, axis=None, dtype=None, out=None) Parameters : 
arr : [array_like] Array containing numbers whose cumulative product is desired.

In [ ]:
 def cumulative_product(list1,n):
    list2=[]
    i=0
    list2.append(list1[i])
    for i in range(1,n):
        v=list1[i]*list2[i-1]
        list2.append(v)
        
    print(list2)
list3=[]
n=int(input("enter size :"))
print("enter the data:")
for i in range(0,n):
    x=int(input())
    list3.append(x)
cumulative_product(list3,n)

AIM: 


 b) Write a function reverse to reverse a list. Without using the reverse function. 

DESCRIPTION: 



In this Python code snippet post, we are going to implement a list reverse function from the 
scratch without using any builtin functions. 
Let us see how... 

Iterative solution 
We can use a for loop to swap the first and last items, the second and the one before the last 
item and so on until the list is reversed in place. The number of iterations needed is half the list 
size. If the list has an odd number of items then the middle item will stay in its place. 

In [ ]:
 def reverse_list(numlist):
    temp=list1[::-1]
    numlist=temp
    return temp
list1=[1,2,3,4]
print("giiven list is :",list1)
print("after reverse function:",reverse_list(list1))
print("after list is:",list1)

AIM: 


 c) Write function to compute gcd, lcm of two numbers. Each function shouldn’t exceed one line. 

DESCRITION:

  Python provides you an anonymous function called lambda. It can take any number of 
arguments, but can only have one expression. It can be used to find LCM and GCD values 
without exceeding each from from one line. 
The general format is

lambda arguments: expression 

The expression is executed during the function call and the result is returned.

Lambda as a Function 

The power of using a lambda expression is implementing it using a function 

In [ ]:
 gcd=lambda a,b: a if b==0 else gcd(a,a%b)
lcm=lambda a,b: (a*b)/gcd(a,b)
 
x=4
y=24
print("gcd=",gcd(x,y))
print("lcm=",lcm(x,y))

 Exercise 11
 - Multi-D Lists
 
a) Write a program that defines a matrix and prints
 
b) Write a program to perform addition of two square matrices
 
c) Write a program to perform multiplication of two square matrices

AIM: 

a)  Write a program that defines a matrix and prints 

DESCRIPTION: 


Lists are a very widely use data structure in python. They contain a list of elements separated by 
comma. But sometimes lists can also contain lists within them. These are called nested lists or 
multidimensional lists. In this article we will see how to create and access elements in a 
multidimensional list. 

Methods on Multidimensional lists 

1. append(): Adds an element at the end of the list. 

2. extend(): Add the elements of a list (or any iterable), to the end of the current list. 

3. reverse(): Reverses the order of the list. 

In [ ]:
 def mat_read(rows,cols):
    mat=[[int(input("Enter the mat[%d,%d] value "%(i,j)))for j in range(cols)]for i in range (rows)]
    return mat
def print_mat(rows,cols,mat):
    for i in range(rows):
        for j in range (cols):
            print(mat[i][j],end='\t')
        print()
    
matA=[[]]
matB=[[]]
mat_sum=[[]]
 
 
rows=int(input("Enter the row size "))
cols=int(input("Enter the column size "))
 
if(rows==cols):
    print("For matrix A")
    matA=mat_read(rows,cols)
    
    print("For matrix B")
    matB=mat_read(rows,cols)
    
    mat_sum=[[matA[i][j]+matB[i][j] for j in range(cols)]for i in range (rows)]
 
    print("Matrix A ")
    print_mat(rows,cols,matA)
    
    print("Matrix B ")
    print_mat(rows,cols,matB)
    
    print("Matrix A+B = ")
    print_mat(rows,cols,mat_sum)
else:
    print("Matrix Addition is not

AIM: 


 b)  Write a program to perform addition of two square matrices 

 
 
   
 
DESCRIPTION: 


We can perform matrix addition in following ways in Python. 

1. Using for loop: 

 
Explanation :- In this program we have used nested for loops to iterate through each row and each column. At each point we add the corresponding elements in the two matrices and store it 
in the result. 

2. Using nested list comprehension : 

In Python, we can implement a matrix as nested list (list inside a list). We can treat each element as a row of the matrix.

Explanation :- 

The output of this program is the same as above. We have used nested list comprehension to iterate through each element in the matrix. List comprehension allows us to write concise codes and we must try to use them frequently in Python. They are very helpful

 
 
3. uising zip function 

 
Explanation : 

The zip function accepts iterator i of each element(list) of matrix, mapping them, adding them 
using sum() and storing them in the map for

In [ ]:
 def mat_read(rows,cols):
    mat=[[int(input("Enter the mat[%d,%d] value "%(i,j)))for j in range(cols)]for i in range (rows)]
    return mat
def print_mat(rows,cols,mat):
    for i in range(rows):
        for j in range (cols):
            print(mat[i][j],end='\t')
        print()
    
matA=[[]]
matB=[[]]
mat_mul=[[]]
 
 
rows=int(input("Enter the row size "))
cols=int(input("Enter the column size "))
 
if(rows==cols):
    print("For matrix A")
    matA=mat_read(rows,cols)
    
    print("For matrix B")
    matB=mat_read(rows,cols)
    
    mat_mul=[[0 for j in range(cols)]for i in range (rows)]
 
    for i in range (rows):
        for j in range(cols):
            for k in range(cols):
                mat_mul[i][j]+=matA[i][k]*matB[k][j]
 
    print("Matrix A ")
    print_mat(rows,cols,matA)
    
    print("Matrix B ")
    print_mat(rows,cols,matB)
    
    print("Matrix A*B = ")
    print_mat(rows,cols,mat_mul)
else:
    print("Matrix multiplication is not

 Exercise - 13 OOP
 
a) Class variables and instance variable and illustration of the self-variable
 
i) Robot
 
ii) ATM Machine

AIM: 


 a)class variables and instance variable and illustration of the self -variable 

DESCRIPTION: 



Variables are named storage location. In python variables are not defined by its type instead it 
will be automatically determined by the value assigned to it. To determine the type of a variable 
a function called type () is used. 

class variableis shared by all object instances of a class. .... They are not defined inside any 
methods of a class. Because a class variable is shared by instances of a class, the Python class 
owns the variable. As a result, all instances of the class will be able to access that variable 

Instance variables are owned by instances of the class. This means that for each object or 
instance of a class, the instance variables are different..... Instance variables, owned by objects 
of the class, allow for each object or instance to have different values assigned to those 
variables 

self variable is used to bind the instance of the class to the instance method. We have to 
explicitly declare it as the first method argument to access the instance variables and methods. 

This variable is used only with the instance methods

1.ATM MACHINE

In [ ]:
 class ATM :
    def _init_(self):
        self.balance=1000
        
    def check_balance(self):
          print("The balance in your account is ::",self.balance)
    def withdraw_balance(self):
        print("Enter balance to withdraw")
        self._init_()
        self.amount=int(input())
        if self.amount>self.balance:
            print("Insuffient amount")
        else:
            self.balance-=self.amount
            self.check_balance()
    def deposite_balance(self):
        print("Enter balance to deposite")
        self._init_()
        self.amount=int(input())
        self.balance=self.balance+self.amount
        self.check_balance()
print("Enter     1 for balance checking\n 2 for balance withdraw\n 3 for balance deposite\n")
a=ATM()
while (True):
    choice=int(input("Enter your choice"))
    if choice==1:
        a.check_balance()
    elif choice==2:
        a.withdraw_balance()
    elif choice==3:
        a.deposite_balance()
    else:
        print("Invalid choice")
        break

2.ROBOT

In [ ]:
 class robot_design ():
    name="chitti"
    speed="1ZB"
    memory="1TB"
    version="1.0"
    def update(self):
        print("Entet your robot name,speed,memory,version")
        self.name=input()
        self.speed=input()
        self.memory=input()
        self.version=input()
    def display(self):
        print("Your robot name,speed,memory,version is ::",self.name,self.speed,self.memory,self.version)
 
r=robot_design()
r.update()
r.display()

 Exercise 12-Modules
a) Install package requests,flasks and explore them.using(pip)
b) write a script that imports requests and fetch content from the page.Eg(wiki)
c) write a simple script that serves a simple HTTPResponse and simple HTML page

AIM: 
 b) Write a scripts that imports requests and fetch content from the page.Eg. (Wiki)code: 

DESCRIPTION: 


The Hypertext Transfer Protocol (HTTP) is an application protocol for distributed, collaborative, 
hypermedia information systems. HTTP is the foundation of data communication for the World 
Wide Web. 

Python requests 
Requests is a simple and elegant Python HTTP library. It provides methods for accessing Web 

resources via HTTP. 

Python requests reading a web page 

The get() method issues a GET request; it fetches documents identified by the given URL. 

In [ ]:
 import requests
 
r=requests.get('https://www.google.com')
 
print("Statuscode:",r.status_code)
 
print("Header Content:",r.headers['content-type'])
print(r.text)

AIM: 

 a) Install packages requests,flask and explore them using(pip) 

DESCRIPTION:





Installing the pip Python package manager on Windows If you are on Windows, and your installed Python the current version, you already have pip! If your Python installation is not the most recent, the easiest thing to do is to simply reinstall it. Download the Python Windows installer at hhtps://www.python.org/downloads/. In Windows, the variable that controls which programs are accessible from the command line is path. To modify your path to include Python and pip, we have to add C:\Python27 and C:\Python27\Tools. Edit the Windows path by opening the Windows menu, right-clicking on Computer and clicking on Properties. Under Advanced system settings, click Environment Variables. Scroll down until you find Path, double-click it, and add ;C:\Python27;C:\Python27\Tools to the end.


Installing packages: Suppose you want to install a package called requests (which is used to make HTTP requests). You need to issue the following command. pip install requests show installed packages You can use the following command to get information about a installed package, i.e Package name, version, location, dependencies. pip show package_name



install flask On Mac and Linux, because you are installing programs outside the user-owned folders, you might have to prepend sudo to the install commands. To install Flask, simply run this: $ pip install flask

show installed flask You can use the following command to get information about a installed flask, i.e Package name, version, location, dependencies $ pip show flask

In [ ]:
 from flask import Flask,render_template
app=Flask(__name__)
print(app)
@app.route("/")
def main():
  return render_template("login.html')
if__name__=="__main__":
  app.run(host="127.0.0.1",port=2500)

AIM: 


 c) Write a simple script that serves a simple HTTPResponse and Simple HTML page. 

DESCRIPTION: 


HTTP Protocol 
The most important part of a web server is HTTP protocol.So now we will see what exactly this 
is – 

It stands for Hyper Text Transfer Protocol. 

It is an application layer protocol that allows web based applications to communicate and 
exchange data. 

The HTTP is the messenger of web. 

The computer that communicate via the HTTP must speak the HTTP protocol. 
It is a TCP/IP based protocol. 

It is used to deliver contents, for eg. images, audios, videos, documents etc. 
Using HTTP is the most convenient way to quickly and reliably move data on the web. 

HTML stands for hypertext markup language. It is the standard markup language for web pages 

that define the structure of the content. These elements are the building blocks of any website

In [ ]:
PROGRAM: 
 
  
from flask import Flask,render_template 
app=Flask( name ) 
print(app) 
@app.route("/") 
 
def main(): 
return render_template('abc.html') 
 if name ==" main ": 
app.run(host="127.0.0.1",port=2500) 
 
 
<Flask ' main '> 

 
 
* Serving Flask app " main " (lazy loading) 
* Environment: production 
WARNING: This is a development server. Do not use it in a production deployment. 
Use a production WSGI server instead. 
* Debug mode: off 
* Running on http://127.0.0.1:2500/ (Press CTRL+C to quit) 

 Exercise14:GUI,Graphics
1.Write a GUI for an Expression Calculator using tk.
2.Write a program to implement the following figures using turtle

AIM:
a. Write a GUI for an Expression Calculator using tk 

DESCRIPTION: 


Tkinter is a Python package which comes with many functions and methods that can be used to 
create an application. In order to create a tkinter application, we generally create an instance of 
tkinter frame, i.e., Tk(). It helps to display the root window and manages all the other 
components of the tkinter application. We can initialize the tkinter instance by assigning the 
variable to it. 

In [ ]:
 import turtle
c=["red","green","blue"]
i=0
turtle.pensize(5)
 
for angle in range(0,360,30):
    if i>2:
        i=0
    turtle.color(c[i])
    turtle.seth(angle)
    turtle.circle(50)
    i+=1

AIM: 

 b. Write a program to implement the following figures using turtle 

DESCRIPTION: 


The turtle module is an extended reimplementation of the same-named module from the Python 
standard distribution up to version Python 2.5. 
It tries to keep the merits of the old turtle module and to be (nearly) 100% compatible with it. 
This means in the first place to enable the learning programmer to use all the commands, 
classes and methods interactively when using the module from within IDLE run with the -n 
switch. 
The turtle module provides turtle graphics primitives, in both object-oriented and procedure- 
oriented ways. Because it uses tkinter for the underlying graphics, it needs a version of Python 
 
 
installed with Tk support.

In [ ]:
 import turtle
turtle.pensize(1)
 
for i in range(36):
    for j in range(4):
        turtle.forward(70)
        turtle.left(90)
    turtle.left(10)

 Exercise 15: Testing
a)Write a test case to check the function even numbers which return true on passing a list of all even numbers.
b) Write a test-case to check the function reverse string which returns the reversed string

AIM: 


 a) Write a test-case to check the function even numbers which return True on passing a list of all even numbers 

DESCRIPTION: 


TestCase is used to create test cases by subclassing it. The last block of the code at the bottom 
allows us to run all the tests just by running the file. Basic terms used in the code : assertEqual() 
– This statement is used to check if the result obtained is equal to the expected result 

test case: 
A test case is a set of conditions which is used to determine whether a system under test works 
correctly.

In [ ]:
 def evnNo(num):
    stat=True
 
    for i in num:
        if i%2 ==1:
            stat=False
            break
    return stat
        
numbers=[]
for i in range(0,2):
    numbers.append(int(input("Enter a value")))
print(evnNo(numbers))

Enter a value4
Enter a value2
True


AIM: 


b) Write a test-case to check the function reverse string which returns the reversed string 

DESCRIPTION:


Python string library does’nt support the in-built “reverse()” as done by other python containers 
like list, hence knowing other methods to reverse string can prove to be useful. This article 
discusses several ways to achieve it. 
The reversed() returns the reversed iterator of the given string and then its elements are joined 
empty string separated using join(). And reversed order string is formed. 

In [ ]:
 def rev_str(st):
    return st[::-1]
 
st="swarnandhra"
print("Given String is: ",st)
 
print("Reverse is: ",rev_str(st))

Given String is:  swarnandhra
Reverse is:  arhdnanraws


 Exercise - 16 - Advanced
a) Build any one classical data structure.
b) Write a program to solve knapsack problem

AIM: 


 a) Build any one classical data structure. 

DESCRIPTION: 


What is a Data Structure? 
Organizing, managing and storing data is important as it enables easier access and eficient 
modifications. Data Structures allows you to organize your data in such a way that enables you 
to store collections of data, relate them and perform operations on them accordingly. 


Stack Stacks are linear Data Structures which are based on the principle of Last-In-First-Out 
(LIFO) where data which is entered last will be the first to get accessed. It is built using the array 
structure and has operations namely, pushing (adding) elements, popping (deleting) elements 
and accessing elements only from one point in the stack called as the TOP. This TOP is the 
pointer to the current position of the stack. Stacks are prominently used in applications such as 
Recursive Programming, reversing words, undo mechanisms in word editors and so forth. 

In [ ]:
 import sys
a=[]
while True: 
print("1.PUSH 2.POP 3.DISPLAY 4.EXIT")
 ch=int(input("Enter Your Choice: "))
if ch==1:
    ele=int(input("Enter element: "))
    a.append(ele).
    print ("Inserted") 
elif ch==2:
  if len(a)==0: 
     print("\t STACK IS EMPTY")
  else:
     print("Deleted element is: ", a[len(a)-1])
     a.remove (a [len (a) -1])
elif ch==3:
  if len(a)==0:
     print("\t STACK IS EMPTY")
  else:
     print("\tThe Elements in Stack is: ") 
     for i in reversed(a):
       print (i)
elif ch==4: 
   sys.exit()
else: 
   print("\tINVALID CHOICE")

AIM:  

Enter Element: 16 

b) Write a program to solve knapsack problem 

DESCRIPTION: 


Python Program for 0-1 Knapsack Problem 
Problem statement − We are given weights and values of n items, we need to put these items in 
a bag of capacity W up to the maximum capacity w. We need to carry a maximum number of 
items and return its 
value. Brute-force 
approach

In [ ]:
 def knapSack(W,wt,val,n): 
 K=[[0 for x in range(W+1)] for x in range(n+1)]
for i in range(n+1):
  for w in range(W+1):
   if i==0orw==0:
      K[i][w]=0
   elif wt[i-1]<=w:
      K[i][w]=max(val[i-1]+ K[i-1][w-wt[i-1]],K[i-1][w]) 
   else:
      K[i][w]=K[i-1][w]
return K[n][W]
val= [5,3,4]
wt=[3,2,1]
W=5
n=len(val)
print("Maximum value knapsack of capacity W: ",

 Exercise - 17-Data Analysis
Data analysis or manipulation using the following packages
a) Numpy b) Pandas
Exercise - 17 - Advanced Data analysis or manipulation using the following packages
a) Scipy b) matplotlib

AIM:
 
  
1. Data analysis or manipulation using the following packages 
a) Numpy b) Pandas a) Scipy b) matplotlib 

DESCRIPTION: 


Learn how to analyze data using Python..... It includes following parts: Data Analysis libraries: 
will learn to use Pandas, Numpy and Scipy libraries to work with a sample dataset. We will 
introduce you to pandas, an open-source library, and we will use it to load, manipulate, analyze, 
and visualize cool datasets. 


SciPy is a free and open-source Python library used for scientific computing and technical 
computing. It is a collection of mathematical algorithms and convenience functions built on the 

NumPy extension of Python

NumPy is the fundamental package for scientific computing in Python. .... NumPy arrays 
facilitate advanced mathematical and other types of operations on large numbers of data. 

Matplotlib is a plotting library for the Python programming language and its numerical 
mathematics extension NumPy. It provides an object-oriented API for embedding plots into 
applications using general-purpose GUI toolkits like Tkinter, wxPython, Qt, or GTK 

Pandas is an open source Python package that is most widely used for data science/data 

analysis and machine learning tasks. It is built on top of another package named Numpy, which 
provides support for multi-dimensional arrays. 
Scikit-learn is probably the most useful library for machine learning in Python. The sklearn 

library contains a lot of eficient tools for machine learning and statistical modeling including 

classification, regression, clustering and dimensionality reduction. 
Seaborn is a library in Python predominantly used for making statistical graphics. Seaborn is a 
data visualization library built on top of matplotlib and closely integrated with pandas data 

structures in Python

In [ ]:
 import sys
 
print('Python:{}'.format(sys.version))
 
#scipy
 
import scipy
print('scipy: {}'.format(scipy.__version__))
 
#numpy 
 
import numpy
print('numpy:{}'.format(numpy.__version__))
 
#matplotlib 
 
import matplotlib
print('matplotlib:{}'.format(matplotlib.__version__))
 
#pandas 
 
import pandas
print('pandas:{}'.format(pandas. __version__))
 
#scikit-learn
 
import sklearn
print('sklearn:{}'.format(sklearn.__version__))
 
import seaborn
print('seaborn: {}'.format(seaborn.__version__)) 
 
import urllib
print('urlib:{}'.format(urllib.__name__)) 
 
import csv
print('csv: {}'.format(csv.__version__))

Python:3.7.11 (default, Jul  3 2021, 18:01:19) 
[GCC 7.5.0]
scipy: 1.4.1
numpy:1.19.5
matplotlib:3.2.2
pandas:1.1.5
sklearn:0.22.2.post1
seaborn: 0.11.1
urlib:urllib
csv: 1.0


In [ ]:
NumPy  
 
import numpy as np 
a=np.array([0,1,2]) 
print(type(a)) 
print(a.shape) 
print(a[0]) 
print(a[1]) 
print(a[2]) 
a[0]=5 
print(a) 
 
 
<class 'numpy.ndarray'> 
(3,) 
0 
1 
2 
[5 1 2] 

 
 
 
import numpy as np 
b=np.array([[0,1,2],[3,4,5]]) 
print(b.shape) 
print(b) 
print(b[0,0],b[0,1],b[1,0]) 
 
 
(2, 3) 
[[0 1 2] 
[3 4 5]] 
0 1 3 
  
import numpy as np 
a=np.zeros((3,3)) 
print(a) 
 
[[0. 0. 0.] 
[0. 0. 0.] 
[0. 0. 0.]] 
  
import numpy as np 
b=np.ones((2,2)) 
print(b) 
 
[[1. 1.] 
[1. 1.]] 
  
import numpy as np 
c=np.full((3,3),7) 
print(c) 
 
[[7 7 7] 
[7 7 7] 
[7 7 7]] 
  
import numpy as np 
d=np.random.random((3,3)) 
print(d) 
 
[[0.81016965 0.93708625 0.64555727] 
[0.69457725 0.87169481 0.89364639] 
[0.10066267 0.41921179 0.16202094]] 
  
import numpy as np 
e=np.eye(3) 
print(e) 
 
[[1. 0. 0.] 
[0. 1. 0.] 
[0. 0. 1.]] 
  
import numpy as np 
 
 
 
f=np.array([2,3,1,0]) 
print(f) 
 
[2 3 1 0] 
  
import numpy as np 
g=np.arange(2,10) 
print(g) 
 
[2 3 4 5 6 7 8 9] 
  
import numpy as np 
h=np.array([[0,1,2.0],[0,0,0],(1+1j,3.,2.)]) 
print(h) 
 
[[0.+0.j 1.+0.j 2.+0.j] 
[0.+0.j 0.+0.j 0.+0.j] 
[1.+1.j 3.+0.j 2.+0.j]] 
  
import numpy as np 
i=np.arange(1,8,dtype=np.float) 
print(i) 
 
[1. 2. 3. 4. 5. 6. 7.] 
  
import numpy as np 
j=np.linspace(2.,4., 5) 
print(j) 
 
[2. 2.5 3. 3.5 4. ] 
  
import numpy as np 
k=np.indices((3,3)) 
print(k) 
 
[[[0 0 0] 
[1 1 1] 
[2 2 2]] 
 
[[0 1 2] 
[0 1 2] 
[0 1 2]]] 
  
import numpy as np 
x=np.array([0,1]) 
y=np.array([2.0,3.0]) 
z=np.array([5,6], dtype=np.int64) 
print(x.dtype,y.dtype,z.dtype) 
 
int64 float64 int64 
  
import numpy as np 
x=np array([5 6 7 8 9]) 
 
 
 
 
print(x[1:7:2]) 
print(x[-2:5]) 
print(x[-1:1:-1]) 
 
[6 8] 
[8 9] 
[9 8 7] 
  
import numpy as np 
a=np.array([[1,2],[3,4],[5,6]]) 
print(a>2) 
print(a[a>2]) 
 
[[False  False] 
[  True  True] 
[ True  True]] 
[3 4 5 6] 
  
import numpy as np 
x=np.array([[1,2],[3,4],[5,6]]) 
y=np.array([[7,8],[9,10],[11,12]]) 
print(x+y) 
print(np.add(x,y)) 
print(x-y) 
print(np.subtract(x,y)) 
 
[[ 8 10] 
[12 14] 
[16 18]] 
[[ 8 10] 
[12 14] 
[16 18]] 
[[-6 -6] 
[-6 -6] 
[-6 -6]] 
[[-6 -6] 
[-6 -6] 
[-6 -6]] 
  
import numpy as np 
x=np.array([[1,2],[3,4],[5,6]]) 
y=np.array([[7,8],[9,10],[11,12]]) 
print(np.multiply(x,y)) 
print(x*y) 
 
[[ 7 16] 
[27 40] 
[55 72]] 
[[ 7 16] 
[27 40] 
[55 72]] 
  
import numpy as np 
x=np.array([[1,2],[3,4],[5,6]]) 
y=np.array([[7,8],[9,10],[11,12]]) 
 
 
 
 
print(np.divide(x,y)) 
print(x/y) 
 
[[0.14285714 0.25 ] 
[0.33333333 0.4 ] 
[0.45454545 0.5 ]] 
[[0.14285714 0.25 ] 
[0.33333333 0.4 ] 
[0.45454545 0.5 ]] 
 
 
import numpy as np 
x=np.array([[1,2],[3,4],[5,6]]) 
print(np.sqrt(x)) 
 
[[1. 1.41421356] 
[1.73205081 2. ] 
[2.23606798 2.44948974]] 
  
import numpy as np 
a=np.array([9,10]) 
b=np.array([11,12]) 
print(a.dot(b)) 
print(np.dot(a,b)) 
 
219 
219 
  
import numpy as np 
a=np.array([9,10]) 
x=np.array([[1,2],[3,4]]) 
print(x.dot(a)) 
print(np.dot(x,a)) 
 
[29 67] 
[29 67] 
 
 
import numpy as np 
x=np.array([[1,2],[3,4]]) 
y=np.array([[5,6],[7,8]]) 
print(x.dot(y)) 
print(np.dot(x,y)) 
 
[[19 22] 
[43 50]] 
[[19 22] 
[43 50]] 
 
 
import numpy as np 
x=np.array([[1,2],[3,4]]) 
print(np.sum(x)) 
print(np.sum(x,axis=0)) 
print(np.sum(x,axis=1))  
 
 
10 
[4 6] 
[3 7] 
  
import numpy as np 
x=np.array([[1,2],[3,4]]) 
print(x) 
print(x.T) 
 
 
[[1 2] 
[3 4]] 
[[1 3] 
[2 4]] 
  
import numpy as np 
v=np.array([1,2,3]) 
print(v) 
print(v.T) 
 
[1 2 3] 
[1 2 3] 
  
import numpy as np 
a=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
v=np.array([1,0,1]) 
b=a+v 
print(b) 
 
[[ 2  2  4] 
[ 5  5  7] 
[ 8 8 10]] 
  
import numpy as np 
x=np.array([[1,2,1],[3,4,1]]) 
print("X.T:\n",x.T) 
w=np.array([1,1]) 
print("W:\n",w) 
print("Final :\n",(x.T+w).T) 
X.T: 
[[1 3] 
[2 4] 
[1 1]] 
W: 
[1 1] 
Final : 
[[2 3 2] 
[4 5 2]] 
  
import numpy as np 
x=np.array([[1,2,1],[3,4,1]]) 
print(x*2) 
 
 
 
 
[[2 4 2] 
[6 8 2]] 
  
import numpy as np 
np.random.rand(3,2) 
 
array([[0.10074037, 0.27068697], 
[0.48588216, 0.77310637], 
[0.5907359 , 0.25493591]]) 
  
import numpy as np 
np.random.rand(10) 
 
array([0.18952105, 0.81924627, 0.98824282, 0.0406113 , 0.81100701, 
0.24091875, 0.96118339, 0.87948378, 0.96721396, 0.09074509]) 
  
import random 
print (random.randint(0,9))
8

Pandas


1.Creating Series

In [ ]:
 
import pandas as pd 
s=pd.Series([1,2,3,4,5],index=['A','B','C','D','E']) 
s  
A 1 
B 2 
C 3 
D 4 
E 5 
dtype: int64

2. Data Frames

In [ ]:
import pandas as pd 
data={'Gen':['F','M','M'],'EiD':['E01','E02','E03'],'Age':[25,45,38]} 
 
df=pd.DataFrame(data,columns=['EiD','Age','Gen']) 
print(df) 
 
EiD Age Gen 
 
 
 
0  E01   25   F 
1  E02   45   M 
2  E03   38   M 
  
import pandas as pd 
from numpy import loadtxt 
from urllib.request import urlopen 
url='https://raw.githubusercontent.com/jbrownlee/datasets/master/pima-indians-diabetes.data.csv' 
raw_data=pd.read_csv(urlopen(url)) 
raw_data.shape 
 
 
(767, 9) 
  
raw_data.head() 
  
6 148 72 35 0 33.6 0.627 50 1   
0 1 85 66 29 0 26.6 0.351 31 0 
1 8 183 64 0 0 23.3 0.672 32 1 
2 1 89 66 23 94 28.1 0.167 21 0 
3 0 137 40 35 168 43.1 2.288 33 1 
4 5 116 74 0 0 25.6 0.201 30 0 
 
 raw_data.tail() 
        
 
6 148 72 35 0 33.6 0.627 50 1 
762 10 101 76 48 180 32.9 0.171 63 0 
763 2 122 70 27 0 36.8 0.340 27 0 
764 5 121 72 23 112 26.2 0.245 30 0 
765 1 126 60 0 0 30.1 0.349 47 1 
766 1 93 70 31 0 30.4 0.315 23 0 
 
 
raw_data.head(25) 

 
 
20 8 99 84 0 0 35.4 0.388 50 0 
 
21 7 196 90 0 0 39.8 0.451 41 1 
 
22 9 119 80 35 0 29.0 0.263 29 1 
 
23 11 143 94 33 146 36.6 0.254 51 1 
 
24 10 125 70 26 115 31.1 0.205 41 1 
 6 148 72 35 0 33.6 0.627 50 1 
0 1 85 66 29 0 26.6 0.351 31 0 
1 8 183 64 0 0 23.3 0.672 32 1 
2 1 89 66 23 94 28.1 0.167 21 0 
3 0 137 40 35 168 43.1 2.288 33 1 
4 5 116 74 0 0 25.6 0.201 30 0 
5 3 78 50 32 88 31.0 0.248 26 1 
6 10 115 0 0 0 35.3 0.134 29 0 
7 2 197 70 45 543 30.5 0.158 53 1 
8 8 125 96 0 0 0.0 0.232 54 1 
9 4 110 92 0 0 37.6 0.191 30 0 
10 10 168 74 0 0 38.0 0.537 34 1 
11 10 139 80 0 0 27.1 1.441 57 0 
12 1 189 60 23 846 30.1 0.398 59 1 
13 5 166 72 19 175 25.8 0.587 51 1 
14 7 100 0 0 0 30.0 0.484 32 1 
15 0 118 84 47 230 45.8 0.551 31 1 
16 7 107 74 0 0 29.6 0.254 31 1 
17 1 103 30 38 83 43.3 0.183 33 0 
18 1 115 70 30 96 34.6 0.529 32 1 
19 3 126 88 41 235 39.3 0.704 27 0 
 
raw_data.describe()  
6 148 72 35 0 33.6 0.627   
count 767.000000 767.000000 767.000000 767.000000 767.000000 767.000000 767.000000 767. 
mean 3.842243 120.859192 69.101695 20.517601 79.903520 31.990482 0.471674 33. 
std 3.370877 31.978468 19.368155 15.954059 115.283105 7.889091 0.331497 11. 
min 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.078000 21. 
25% 1.000000 99.000000 62.000000 0.000000 0.000000 27.300000 0.243500 24. 
50% 3.000000 117.000000 72.000000 23.000000 32.000000 32.000000 0.371000 29. 
75% 6.000000 140.000000 80.000000 32.000000 127.500000 36.600000 0.625000 41. 
max 17.000000 199.000000 122.000000 99.000000 846.000000 67.100000 2.420000 81. 
 
 
raw_data.cov() 

 
 
   6 148 72 35 0 33.6 0.627  
6 11.362809 13.888985 9.218414 -4.436515 -28.367721 0.465859 -0.037912 21 
148 13.888985 1022.622445 94.451675 28.764884 1225.357154 55.742783 1.451278 98 
72 9.218414 94.451675 375.125415 64.058260 198.939328 43.054755 0.264396 54 
35 -4.436515 28.764884 64.058260 254.532001 805.536948 49.407935 0.970472 -21 
0 -28.367721 1225.357154 198.939328 805.536948 13290.194335 180.177540 7.092087 -55 
33.6 0.465859 55.742783 43.054755 49.407935 180.177540 62.237755 0.367558 3 
0.627 -0.037912 1.451278 0.264396 0.970472 7.092087 0.367558 0.109890 0 
50 21.551571 98.618350 54.531221 -21.725792 -55.469702 3.329503 0.127544 138 
1 0.355250 7.101300 0.599018 0.557181 7.252951 1.100707 0.027376 1 
 
 raw_data.corr() 
         
 
6 148 72 35 0 33.6 0.627 50  
6 1.000000 0.128846 0.141197 -0.082495 -0.072999 0.017518 -0.033927 0.544018 0.221 
148 0.128846 1.000000 0.152498 0.056381 0.332383 0.220955 0.136903 0.262408 0.465 
72 0.141197 0.152498 1.000000 0.207308 0.089098 0.281777 0.041180 0.239571 0.064 
35 -0.082495 0.056381 0.207308 1.000000 0.437974 0.392553 0.183498 -0.115873 0.073 
0 -0.072999 0.332383 0.089098 0.437974 1.000000 0.198111 0.185579 -0.040942 0.131 
33.6 0.017518 0.220955 0.281777 0.392553 0.198111 1.000000 0.140546 0.035911 0.292 
0.627 -0.033927 0.136903 0.041180 0.183498 0.185579 0.140546 1.000000 0.032738 0.173 
50 0.544018 0.262408 0.239571 -0.115873 -0.040942 0.035911 0.032738 1.000000 0.236 
1 0.221087 0.465856 0.064882 0.073265 0.131984 0.292695 0.173245 0.236417 1.000 
 
 
from sklearn.datasets import load_iris 
import numpy as np 
iris=load_iris() 
iris 
 
{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n :Num 
'data': array([[5.1, 3.5, 1.4, 0.2], 
[4.9, 3. , 1.4, 0.2], 
[4.7, 3.2, 1.3, 0.2], 
[4.6, 3.1, 1.5, 0.2], 
[5. , 3.6, 1.4, 0.2], 
[5.4, 3.9, 1.7, 0.4], 
[4.6, 3.4, 1.4, 0.3], 
[5. , 3.4, 1.5, 0.2], 
[4.4, 2.9, 1.4, 0.2], 
[4.9, 3.1, 1.5, 0.1], 
[5.4, 3.7, 1.5, 0.2], 
[4.8, 3.4, 1.6, 0.2], 

 
 
[4.8, 3. , 1.4, 0.1], 
[4.3, 3. , 1.1, 0.1], 
[5.8, 4. , 1.2, 0.2], 
[5.7, 4.4, 1.5, 0.4], 
[5.4, 3.9, 1.3, 0.4], 
[5.1, 3.5, 1.4, 0.3], 
[5.7, 3.8, 1.7, 0.3], 
[5.1, 3.8, 1.5, 0.3], 
[5.4, 3.4, 1.7, 0.2], 
[5.1, 3.7, 1.5, 0.4], 
[4.6, 3.6, 1. , 0.2], 
[5.1, 3.3, 1.7, 0.5], 
[4.8, 3.4, 1.9, 0.2], 
[5. , 3. , 1.6, 0.2], 
[5. , 3.4, 1.6, 0.4], 
[5.2, 3.5, 1.5, 0.2], 
[5.2, 3.4, 1.4, 0.2], 
[4.7, 3.2, 1.6, 0.2], 
[4.8, 3.1, 1.6, 0.2], 
[5.4, 3.4, 1.5, 0.4], 
[5.2, 4.1, 1.5, 0.1], 
[5.5, 4.2, 1.4, 0.2], 
[4.9, 3.1, 1.5, 0.2], 
[5. , 3.2, 1.2, 0.2], 
[5.5, 3.5, 1.3, 0.2], 
[4.9, 3.6, 1.4, 0.1], 
[4.4, 3. , 1.3, 0.2], 
[5.1, 3.4, 1.5, 0.2], 
[5. , 3.5, 1.3, 0.3], 
[4.5, 2.3, 1.3, 0.3], 
[4.4, 3.2, 1.3, 0.2], 
[5. , 3.5, 1.6, 0.6], 
[5.1, 3.8, 1.9, 0.4], 
[4.8, 3. , 1.4, 0.3], 
[5.1, 3.8, 1.6, 0.2], 
[4.6, 3.2, 1.4, 0.2], 
[5.3, 3.7, 1.5, 0.2], 
[5. , 3.3, 1.4, 0.2], 
[7. , 3.2, 4.7, 1.4], 
[6.4, 3.2, 4.5, 1.5], 
[6.9, 3.1, 4.9, 1.5], 
[5.5, 2.3, 4. , 1.3], 
[6.5, 2.8, 4.6, 1.5], 
[5.7, 2.8, 4.5, 1.3], 
[6.3, 3.3, 4.7, 1.6], 
 
 
X=pd.DataFrame(iris.data) 
X 
 
 
145 6.7 3.0 5.2 2.3 
 
146 6.3 2.5 5.0 1.9 
 
147 6.5 3.0 5.2 2.0 
 
148 6.2 3.4 5.4 2.3 
 
149 5.9 3.0 5.1 1.8 
 
150 rows × 4 columns 
  0 1 2 3 
0 5.1 3.5 1.4 0.2 
1 4.9 3.0 1.4 0.2 
2 4.7 3.2 1.3 0.2 
3 4.6 3.1 1.5 0.2 
4 5.0 3.6 1.4 0.2 
... ... ... ... ... 
  
X.shape 
(150,4) 
X.columns=['Sepal_length','Sepal_width','petal_length','petal_width'] 
X.head() 
  
 Sepal_length Sepal_width petal_length petal_width 
0 5.1 3.5 1.4 0.2 
1 4.9 3.0 1.4 0.2 
2 4.7 3.2 1.3 0.2 
3 4.6 3.1 1.5 0.2 
4 5.0 3.6 1.4 0.2 
 X.tail() 
    
 
Sepal_length Sepal_width petal_length petal_width 
145 6.7 3.0 5.2 2.3 
146 6.3 2.5 5.0 1.9 
147 6.5 3.0 5.2 2.0 
148 6.2 3.4 5.4 2.3 
149 5.9 3.0 5.1 1.8 
 X.describe() 
    
 
 
 
std 0.828066 0.435866 1.765298 0.762238 
min 4.300000 2.000000 1.000000 0.100000 
 
25% 5.100000 2.800000 1.600000 0.300000 
 
50% 5.800000 3.000000 4.350000 1.300000 
 
75% 6.400000 3.300000 5.100000 1.800000 
max 7.900000 4.400000 6.900000 2.500000 
   Sepal_length Sepal_width petal_length petal_width 
count 150.000000 150.000000 150.000000 150.000000 
mean 5.843333 3.057333 3.758000 1.199333 
 
 
X.cov()  
 
Sepal_length 
 
 
Sepal_width 
 
 
petal_length 
 
 
petal_width 
Sepal_length 0.685694 -0.042434 1.274315 0.516271 
Sepal_width -0.042434 0.189979 -0.329656 -0.121639 
petal_length 1.274315 -0.329656 3.116278 1.295609 
petal_width 0.516271 -0.121639 1.295609 0.581006 
 X.corr() 
    
 
Sepal_length Sepal_width petal_length petal_width 
Sepal_length 1.000000 -0.117570 0.871754 0.817941 
Sepal_width -0.117570 1.000000 -0.428440 -0.366126 
petal_length 0.871754 -0.428440 1.000000 0.962865 
petal_width 0.817941 -0.366126 0.962865 1.000000 
 
 
import numpy as np 
df=pd.DataFrame({'Name':['Pooji','Nani','Chinni','Chikki'],'state':['IND','USA','UK','USSR'],'Grade':['A','A','B','C'],'Age': np. 
print(df) 
 
Name state Grade Age salary 
0   JAYA   IND A  30.906880  3595.154133 
1 GAYATRI   USA A  34.991981  4261.790535 
2  KEERTHI UK B  33.773451  4475.564708 
3  REVATHI  USSR C 33.556051 3680.246936 
  
import numpy as np 
import pandas as pd 
df=pd.DataFrame({'Name':['Pooji','Nani','Chinni','Chikki'],'state':['IND','USA','UK','USSR'],'Grade':['A','A','B','C'],'Age': np. 
df.groupby(['Name','state']).max() 

SCIPY

In [ ]:
 
 
 
Grade Age salary 
 
Name state 
 
Chikki USSR C 29.794042 4609.179273 
Chinni UK B 26.926079 3885.134254 
 
Nani USA A 29.096474 3512.814611 
 
Pooji IND A 26.294071 3363.990431 
 
 
  
import numpy as np 
np.linspace(1.,4.,6) 
 
array([1. , 1.6, 2.2, 2.8, 3.4, 4. ]) 
  
from scipy.cluster.vq import kmeans,vq,whiten 
from numpy import vstack,array 
from numpy.random import rand 
 data=vstack((rand(100,3)+array([.5,.5,.5]),rand(100,3))) 
data 
 
array([[0.90258909, 0.9233607 , 0.78273525], 
[0.59467738, 1.02911659, 0.88358223], 
[0.92905869, 0.80844347, 0.82420722], 
[1.06828604, 0.81638002, 0.88543623], 
[0.76992404, 1.26167714, 1.10877409], 
[0.94258935, 1.0448952 , 1.06661058], 
[0.58711959, 0.74227861, 0.79150924], 
[1.19399041, 1.33268416, 0.61880348], 
[1.44290692, 1.36136538, 0.78877052], 
[1.03774349, 0.6544453 , 0.51597171], 
[0.85270142, 1.09004265, 1.46484699], 
[1.49274988, 1.22665456, 0.61984447], 
[1.40821041, 1.41990694, 1.30399566], 
[1.15292093, 1.47797535, 1.49433546], 
[1.23392988, 1.28656044, 1.19497233], 
[1.30474702, 1.17295312, 0.99283884], 
[1.11447917, 1.05786207, 1.20734399], 
[0.57127275, 1.00986092, 0.7823292 ], 
[0.65881379, 0.5586953 , 1.19068023], 
[0.63549054, 1.43347337, 1.20934843], 
[1.29225155, 1.18181672, 1.02012635], 
[1.29555226, 0.97626639, 1.485882  ], 
[0.64667569, 0.69919071, 1.1864496 ], 
[0.93023392, 0.91972667, 1.2469598 ], 
[0.82753469, 0.96163331, 1.01320967], 
[1.49970107, 0.50047758, 1.2111403 ], 
[1.01357654, 0.87647747, 1.24656772], 
[1.45615945, 1.42696013, 0.62253123], 
[1.06189792, 1.49445231, 0.63966425], 
[0.84649455, 1.35510061, 1.48476767], 
[0.97081189, 1.29297546, 1.26874188], 
[1.20442852, 0.91949897, 0.88777343], 
[0.95969091, 0.73892865, 0.5579961 ], 
[0.74723184, 0.59132549, 0.66483177], 
[0.5757808 , 0.77717716, 1.23873048], 
[1.21637942, 1.30881095, 1.14530707], 
[0.66188824, 1.04102459, 0.62415182], 
[1.48653083, 0.93795358, 1.32296478], 
[0.76699392, 1.14114594, 0.70449482], 
[0.9997548 , 0.87533817, 0.8307093 ], 
Scipy 

 
 
[0.53980197, 0.53559352, 0.70849509], 
[0.84755593, 1.30884233, 1.11748818], 
[0.61598479, 0.92493323, 0.62984949], 
[0.58814621, 1.43817664, 1.00232063], 
[1.02392348, 0.98574837, 0.83436041], 
[1.16143734, 0.63678783, 0.60890533], 
[1.45800622, 1.31447604, 1.20930403], 
[1.14004837, 0.94355688, 0.59025659], 
[0.98340077, 1.04390078, 0.6218841 ], 
[1.07777382, 1.41688591, 0.86597751], 
[1.17337323, 0.68930459, 0.54606734], 
[0.78309997, 0.70960006, 0.8653093 ], 
[0.8879114 , 0.83011562, 1.24778146], 
[0.85948029, 1.14241534, 0.91087691], 
[1.13946389, 1.28495366, 1.23643912], 
[1.26684229, 0.52693652, 1.4311785 ], 
[1.15827702, 1.1111431 , 0.63416144], 
[0 63860458  0 71161294  0 94442562]  
data=whiten(data) 
data 
 
array([[2.41005477, 2.35350275, 2.07361492], 
[1.58788209, 2.62305806, 2.3407778 ], 
[2.48073275, 2.06059662, 2.18348208], 
[2.85249166, 2.08082566, 2.3456894 ], 
[2.05581824, 3.21581873, 2.93735398], 
[2.51686174, 2.66327528, 2.82565481], 
[1.56770161, 1.89195269, 2.0968589 ], 
[3.18814209, 3.39680457, 1.6393284 ], 
[3.85278831, 3.46990853, 2.08960349], 
[2.77093826, 1.66807923, 1.36690744], 
[2.27684685, 2.77834912, 3.88065898], 
[3.98587685, 3.12655163, 1.64208619], 
[3.76014317, 3.61912187, 3.45453314], 
[3.07848012, 3.76712921, 3.95877954], 
[3.29478676, 3.27924238, 3.16570954], 
[3.48387965, 2.98967501, 2.63021939], 
[2.97583459, 2.69632582, 3.19848443], 
[1.52538804, 2.57397835, 2.07253921], 
[1.7591364 , 1.4240274 , 3.15433895], 
[1.69685964, 3.65370059, 3.20379458], 
[3.4505148 , 3.01226693, 2.70250922], 
[3.4593282 , 2.48835113, 3.93638472], 
[1.72672576, 1.78212834, 3.14313121], 
[2.48387081, 2.34424019, 3.30343427], 
[2.20964773, 2.45105368, 2.68418561], 
[4.00443763, 1.27563948, 3.20854158], 
[2.70640872, 2.2340047 , 3.30239558], 
[3.88817466, 3.63709936, 1.64920393], 
[2.83543439, 3.80912642, 1.69459257], 
[2.26027353, 3.45394063, 3.93343266], 
[2.59222038, 3.29559328, 3.36113915], 
[3.21601348, 2.3436598 , 2.35188108], 
[2.56252561, 1.88341416, 1.47823807], 
[1.99522648, 1.50719667, 1.76126611], 
[1.53742525, 1.98090367, 3.28163322], 
[3.24792426, 3.33595546, 3.03413679], 
[1.76734565, 2.65340972, 1.65349718], 
[3.969271  , 2.39069774, 3.50478595], 
 
 
 
[2.04799434, 2.90860345, 1.86634109], 
[2.6695025 , 2.23110081, 2.20070732], 
[3.34197049, 2.13825218, 1.46375119], 
[1.44135611, 1.36514455, 1.87693857], 
[2.26310759, 3.33603546, 2.96043926], 
[1.64477621, 2.3575109 , 1.66859139], 
[1.57044285, 3.6656885 , 2.65533846], 
[2.73403665, 2.51251922, 2.2103798 ], 
[3.10122028, 1.6230731 , 1.61310632], 
[3.89310582, 3.35039492, 3.20367694], 
[3.04410837, 2.40497968, 1.56370224], 
[2.62583465, 2.66074068, 1.64748957], 
[2.87782553, 3.61142174, 2.29413954], 
[3.13309098, 1.75693014, 1.4466365 ], 
[2.09100003, 1.80866015, 2.29236931], 
[2.37086304, 2.11583557, 3.305611  ], 
[2.2949475 , 2.91183896, 2.4130866 ], 
[3.04254773, 3.27514695, 3.27556299], 
[3.38266806, 1.34307921, 3.79146473], 
[3.09278173, 2.83213089, 1.68001457], 
[1.70517462, 1.81379067, 2.50196355], 
 
centroids,_=kmeans(data,3) 
centroids 
 
array([[2.87117126, 2.87609742, 2.77016224], 
[1.80705689, 1.52016619, 2.1138557 ], 
[1.13101776, 1.2148155 , 0.80648608]]) 
  
clx,_=vq(data,centroids) 
clx 
 
array([0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 
0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 
1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 
1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 
1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 0, 
2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 
2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 
2, 2], dtype=int32) 
 
 
from scipy.fftpack import fft 
x=np.array([1.0,2.0,1.0,-1.0,1.5]) 
y=fft(x) 
print("FFT :\n",y) 
 
FFT : 
[ 4.5 -0.j 2.08155948-1.65109876j -1.83155948+1.60822041j 
-1.83155948-1.60822041j 2.08155948+1.65109876j] 
  
from scipy.fftpack import ifft 
yinv=ifft(y) 
print("FFT Inverse:\n",yinv) 
 
 
 
 
FFT Inverse: 
[ 1. +0.j  2. +0.j  1. +0.j -1. +0.j  1.5+0.j] 
  
from scipy.fftpack import dct 
print("DCT:\n",dct(np.array([4.,3.,5.,10.,5.,3.]))) 
 
DCT: 
[ 60. -3.48476592 -13.85640646  11.3137085 6. 
-6.31319305] 
  
from scipy.fftpack import idct 
print("IDCT:\n",idct(np.array([4.,3.,5.,10.,5.,3.]))) 
 
IDCT: 
[ 39.15085889 -20.14213562 -6.45392043 7.13341236 8.14213562 
-3.83035081]

SciPy-Integrated  


 
The general form of quad is scipy.integrate.quad(f,a,b), Where 'f' is the name of the function to 
be integrated. Whereas, 'a' and 'b' are the lower and upper limits, respectively. Let us see an 
example of the Gaussian function, integrated over a range of 0 and 1


 
∫f(x)dx 

In [ ]:
Import scipy.integrate 
from numpy import exp 
f=lambda x:exp(-x**2) 
i=scipy.integrate.quad(f,0,1) 
print(i) 
 
(0.7468241328124271, 8.291413475940725e-15) 

Linear Algebra 


 
x+3y+5z=10 
2x+5y+z=8 
2x+3y+8z=3 * 


 from scipy import linalg 
import numpy as np

In [ ]:
a=np.array([[1,3,5],[2,5,1],[2,3,8]]) 
b=np.array([10,8,3]) 
X=linalg.solve(a,b) 
print(X) 
[-9.28 5.16 0.76]

Finding an Determinant 

In [ ]:
from scipy import linalg 
import numpy as np 
 
A=np.array([[1,2],[3,4]]) 
 x=linalg.det(A) 
print(x) 
-2.0 

Eigen values and Eigen Vectors

In [ ]:
from scipy import linalg 
import numpy as np 
 
A=np.array([[1,2],[3,4]]) 
 l,v=linalg.eig(A) 
print("Eigen Values :\n",l) 
print("Eigen Vectors:\n",v) 
Eigen Values : 
[-0.37228132+0.j 5.37228132+0.j] 
Eigen Vectors: 
[[-0.82456484 -0.41597356] 
[ 0.56576746 -0.90937671]] 

Matplot Library

In [ ]:

 
 
x=np.arange(5) 
y=(35,45,23,27,60) 
 
plt.bar(x,y) 
plt.show() 
 
 
 
 
import numpy as np 
x=np.linspace(0,20,1000) 
y=np.sin(x) 
 
plt.plot(x,y,label='sample Label') 
plt.title('sample plot title') 
plt.xlabel('x axis label') 
plt.ylabel('y axis label') 
plt.grid(True) 
 
plt.figtext(0.5,0.01,'Fig1:Sinusodial', ha='right',va='bottom') 
plt.legend(loc='best',framealpha=0.5,prop={'size':'small'}) 
plt.tight_layout(pad=1) 
plt.show() 